# Generated by Django 5.2.8 on 2025-11-29 02:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon name or emoji', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('task_type', models.CharField(choices=[('daily_practice', 'Luyện tập hàng ngày'), ('correct_answers', 'Trả lời đúng'), ('perfect_week', 'Tuần hoàn hảo'), ('topic_master', 'Bậc thầy chủ đề'), ('streak_master', 'Chuỗi连胜')], max_length=20)),
                ('target_count', models.IntegerField(default=1, help_text='Số lần cần hoàn thành', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('points_reward', models.IntegerField(default=10, help_text='Điểm thưởng khi hoàn thành', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Weekly Task',
                'verbose_name_plural': 'Weekly Tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vietnamese_text', models.TextField()),
                ('english_text', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Dễ'), ('medium', 'Trung bình'), ('hard', 'Khó')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('topic', models.ForeignKey(blank=True, help_text='Chủ đề của câu hỏi', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.topic')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('similarity_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='api.question')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Answer',
                'verbose_name_plural': 'User Answers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyQuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('week_start', models.DateField(help_text='Ngày bắt đầu tuần (Thứ Hai)')),
                ('week_end', models.DateField(help_text='Ngày kết thúc tuần (Chủ Nhật)')),
                ('is_active', models.BooleanField(default=True)),
                ('points_per_question', models.IntegerField(default=5, help_text='Điểm cho mỗi câu trả lời đúng')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('questions', models.ManyToManyField(help_text='Các câu hỏi trong bộ tuần này', related_name='weekly_sets', to='api.question')),
            ],
            options={
                'verbose_name': 'Weekly Question Set',
                'verbose_name_plural': 'Weekly Question Sets',
                'ordering': ['-week_start'],
                'unique_together': {('week_start',)},
            },
        ),
        migrations.CreateModel(
            name='DailyTaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.DateField()),
                ('questions_answered', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('points_earned', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Task Completion',
                'verbose_name_plural': 'Daily Task Completions',
                'ordering': ['-completion_date'],
                'unique_together': {('user', 'completion_date')},
            },
        ),
        migrations.CreateModel(
            name='UserPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('weekly_points', models.IntegerField(default=0)),
                ('current_streak', models.IntegerField(default=0, help_text='Current daily streak')),
                ('longest_streak', models.IntegerField(default=0, help_text='Longest daily streak')),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Points',
                'verbose_name_plural': 'User Points',
                'unique_together': {('user',)},
            },
        ),
        migrations.CreateModel(
            name='WeeklyQuestionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_questions', models.ManyToManyField(blank=True, help_text='Các câu hỏi đã hoàn thành', related_name='weekly_progress', to='api.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_question_progress', to=settings.AUTH_USER_MODEL)),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='api.weeklyquestionset')),
            ],
            options={
                'verbose_name': 'Weekly Question Progress',
                'verbose_name_plural': 'Weekly Question Progress',
                'ordering': ['-question_set__week_start'],
                'unique_together': {('user', 'question_set')},
            },
        ),
        migrations.CreateModel(
            name='UserTaskProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_progress', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('week_start', models.DateField(help_text='Start date of the week')),
                ('points_earned', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_progress', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='api.weeklytask')),
            ],
            options={
                'verbose_name': 'User Task Progress',
                'verbose_name_plural': 'User Task Progress',
                'ordering': ['-week_start', '-updated_at'],
                'unique_together': {('user', 'task', 'week_start')},
            },
        ),
    ]
