# Generated by Django 5.2.8 on 2025-12-10 14:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLearningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(help_text='Ngày học tập')),
                ('exercise_type', models.CharField(choices=[('translation', 'Dịch câu'), ('listening', 'Nghe-viết'), ('mixed', 'Kết hợp')], default='mixed', max_length=20)),
                ('target_questions', models.IntegerField(default=10, help_text='Số câu hỏi mục tiêu', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('completed_questions', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('points_earned', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_learning_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Learning Session',
                'verbose_name_plural': 'Daily Learning Sessions',
                'ordering': ['-session_date'],
                'unique_together': {('user', 'session_date', 'exercise_type')},
            },
        ),
        migrations.CreateModel(
            name='DailyLearningQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('similarity_score', models.FloatField(default=0.0)),
                ('time_taken', models.IntegerField(default=0, help_text='Thời gian trả lời (giây)')),
                ('attempts', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_session_questions', to='api.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_questions', to='api.dailylearningsession')),
            ],
            options={
                'verbose_name': 'Daily Learning Question',
                'verbose_name_plural': 'Daily Learning Questions',
                'ordering': ['created_at'],
                'unique_together': {('session', 'question')},
            },
        ),
        migrations.CreateModel(
            name='DailyLearningSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_target', models.IntegerField(default=10, help_text='Số câu hỏi mục tiêu mỗi ngày', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('preferred_difficulty', models.CharField(choices=[('easy', 'Dễ'), ('medium', 'Trung bình'), ('hard', 'Khó')], default='medium', max_length=20)),
                ('exercise_types', models.CharField(default='translation,listening', help_text='Các loại bài tập (cách nhau bằng dấu phẩy)', max_length=100)),
                ('reminder_enabled', models.BooleanField(default=True)),
                ('reminder_time', models.TimeField(default='09:00:00')),
                ('auto_play_audio', models.BooleanField(default=True)),
                ('speech_rate', models.FloatField(default=1.0, help_text='Tốc độ phát âm (0.5 - 2.0)', validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(2.0)])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_topics', models.ManyToManyField(blank=True, help_text='Chủ đề yêu thích', related_name='user_learning_preferences', to='api.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_learning_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Learning Settings',
                'verbose_name_plural': 'Daily Learning Settings',
                'unique_together': {('user',)},
            },
        ),
        migrations.CreateModel(
            name='DailyLearningStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0, help_text='Chuỗi học tập hiện tại')),
                ('longest_streak', models.IntegerField(default=0, help_text='Chuỗi học tập dài nhất')),
                ('last_learning_date', models.DateField(blank=True, null=True)),
                ('total_days_learned', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_streaks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Learning Streak',
                'verbose_name_plural': 'Daily Learning Streaks',
                'unique_together': {('user',)},
            },
        ),
    ]
